import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
const source=fs.readFileSync(new URL('../lib/server/sellerOrderContract.ts',import.meta.url),'utf8');const exports={};vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports});const price=exports.pricedSellerOrder;
const catalog=[{id:'p1',name:'Protector',brand:'Vexa',variants:[{sku:'V1',size:'250ml',priceRetail:10000,priceWholesale:7500,stock:5}]}];
const body=()=>({customer_id:'10000000-0000-4000-8000-000000000001',client_ref:'20000000-0000-4000-8000-000000000001',items:[{product_id:'p1',sku:'V1',qty:2,expected_price:10000}],notes:'Entrega',payment:5000,method:'Efectivo'});
test('server fixes retail and cost, 25% when explicitly configured',()=>{const result=price(body(),catalog);assert.equal(result.items[0].unit_price,10000);assert.equal(result.items[0].cost_price,7500);assert.equal(result.payment,5000);});
test('preserves actual catalog cost even if not linear',()=>{assert.equal(price(body(),[{...catalog[0],variants:[{...catalog[0].variants[0],priceWholesale:7800}]}]).items[0].cost_price,7800);});
test('rejects owner, totals, price/cost injection and duplicate items',()=>{for(const field of ['seller_id','total','cost_total','status'])assert.throws(()=>price({...body(),[field]:'fake'},catalog));for(const field of ['unit_price','cost_price','name']){const b=body();b.items[0][field]=1;assert.throws(()=>price(b,catalog));}const b=body();b.items.push({...b.items[0]});assert.throws(()=>price(b,catalog));});
test('stale prices conflict and unavailable products cannot be ordered',()=>{const b=body();b.items[0].expected_price=1;assert.throws(()=>price(b,catalog),e=>e.status===409);for(const modify of [{qty:6},{qty:1.5},{sku:'unknown'}]){const b=body();Object.assign(b.items[0],modify);assert.throws(()=>price(b,catalog));}assert.throws(()=>price(body(),[{...catalog[0],variants:[{...catalog[0].variants[0],status:'paused'}]}]));});
test('rejects monetary precision, non-finite and unknown payment methods',()=>{for(const payment of [1.111,Infinity,-1])assert.throws(()=>price({...body(),payment},catalog));assert.throws(()=>price({...body(),method:'fake'},catalog));});

test('Sellers cost is 82 percent of suggested price, independently of wholesale pricing',()=>{const priced=exports.sellerCatalogPricing(catalog);assert.equal(priced[0].variants[0].priceWholesale,8200);assert.equal(catalog[0].variants[0].priceWholesale,7500);assert.equal(exports.sellerCatalogPricing([{...catalog[0],variants:[{...catalog[0].variants[0],priceRetail:123.45}]}])[0].variants[0].priceWholesale,101.23);});
test('free sale price changes the customer total but cannot modify SH cost',()=>{const b=body();Object.assign(b.items[0],{sale_price:12000,expected_cost:8200});const result=price(b,exports.sellerCatalogPricing(catalog));assert.equal(result.items[0].unit_price,12000);assert.equal(result.items[0].cost_price,8200);assert.equal(result.items[0].suggested_price,10000);for(const sale_price of [0,-1,Infinity,1.111,100000001]){b.items[0].sale_price=sale_price;assert.throws(()=>price(b,exports.sellerCatalogPricing(catalog)));}b.items[0].sale_price=12000;b.items[0].expected_cost=7500;assert.throws(()=>price(b,exports.sellerCatalogPricing(catalog)),e=>e.status===409);});
test('retry prices come from the saved order, preserving old cost and chosen sale',()=>{const b=body();b.items[0].sale_price=12000;const saved=[{...catalog[0],variants:[{...catalog[0].variants[0],priceWholesale:7500}]}];assert.equal(price(b,saved).items[0].cost_price,7500);assert.equal(price(b,saved).items[0].unit_price,12000);});
