import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
const source=fs.readFileSync(new URL('../lib/server/sellerOrderContract.ts',import.meta.url),'utf8');const exports={};vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports});const price=exports.pricedSellerOrder;
const catalog=[{id:'p1',name:'Protector',brand:'Vexa',variants:[{sku:'V1',size:'250ml',priceRetail:10000,priceWholesale:7500,stock:5}]}];
const body=()=>({customer_id:'10000000-0000-4000-8000-000000000001',client_ref:'20000000-0000-4000-8000-000000000001',items:[{product_id:'p1',sku:'V1',qty:2,expected_price:10000}],notes:'Entrega',payment:5000,method:'Efectivo'});
test('server fixes retail and cost, 25% when explicitly configured',()=>{const result=price(body(),catalog);assert.equal(result.items[0].unit_price,10000);assert.equal(result.items[0].cost_price,7500);assert.equal(result.payment,5000);});
test('preserves actual catalog cost even if not linear',()=>{assert.equal(price(body(),[{...catalog[0],variants:[{...catalog[0].variants[0],priceWholesale:7800}]}]).items[0].cost_price,7800);});
test('rejects owner, totals, price/cost injection and duplicate items',()=>{for(const field of ['seller_id','total','cost_total','status'])assert.throws(()=>price({...body(),[field]:'fake'},catalog));for(const field of ['unit_price','cost_price','name']){const b=body();b.items[0][field]=1;assert.throws(()=>price(b,catalog));}const b=body();b.items.push({...b.items[0]});assert.throws(()=>price(b,catalog));});
test('stale prices conflict and unavailable products cannot be ordered',()=>{const b=body();b.items[0].expected_price=1;assert.throws(()=>price(b,catalog),e=>e.status===409);for(const modify of [{qty:6},{qty:1.5},{sku:'unknown'}]){const b=body();Object.assign(b.items[0],modify);assert.throws(()=>price(b,catalog));}assert.throws(()=>price(body(),[{...catalog[0],variants:[{...catalog[0].variants[0],status:'paused'}]}]));});
test('rejects monetary precision, non-finite and unknown payment methods',()=>{for(const payment of [1.111,Infinity,-1])assert.throws(()=>price({...body(),payment},catalog));assert.throws(()=>price({...body(),method:'fake'},catalog));});
